webtalk_init -webtalk_dir C:/Users/Jovy/Desktop/MyFile/Desk/Engineer/EE/vivado/projects/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/decoder_38_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr  8 09:21:32 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211915102_0_0_526" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d153a5b0-e06c-423e-ab0a-b9b01c408eb4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cf3922766f544633bcf6c0585fae77c7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "120 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8444_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4089370738 -regid "211915102_0_0_526" -xml C:/Users/Jovy/Desktop/MyFile/Desk/Engineer/EE/vivado/projects/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/decoder_38_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Jovy/Desktop/MyFile/Desk/Engineer/EE/vivado/projects/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/decoder_38_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Jovy/Desktop/MyFile/Desk/Engineer/EE/vivado/projects/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/decoder_38_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
