int order(int degree,int row,int column);
void addrestriction(cnf p,int k);
void addClause(cnf p,int *a,int n);
void addClauses_rule1(cnf p,int degree);
void addClauses_rule2_4(cnf p);
void addClauses_rule2_6(cnf p);
void addClauses_rule2_8(cnf p);
void addClauses_rule2_10(cnf p);
void addClauses_rule2_12(cnf p);
void addClauses_rule2_14(cnf p);
void addClauses_rule2(cnf p,int degree);
void addClauses_rule3_4(cnf p);
void addClauses_rule3_6(cnf p);
void addClauses_rule3_8(cnf p);
void addClauses_rule3_10(cnf p);
void addClauses_rule3_12(cnf p);
void addClauses_rule3_14(cnf p);
void addClauses_rule3(cnf p,int degree);
cnf createSudokuCNF(int degree);
